export const LOGIN = 'LOGIN';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTER = 'REGISTER';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_FULFILLED = 'GET_GROUPS_FULFILLED';
export const GET_GROUPS_REJECTED = 'GET_GROUPS_REJECTED';

export const GET_GROUP = 'GET_GROUP';
export const GET_GROUP_FULFILLED = 'GET_GROUP_FULFILLED';
export const GET_GROUP_REJECTED = 'GET_GROUP_REJECTED';

export const GET_USER = 'GET_USER';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_FULFILLED = 'GET_QUESTION_FULFILLED';
export const GET_QUESTION_REJECTED = 'GET_QUESTION_REJECTED';